### ISSUE TITLE
初始化问题

### ISSUE THREAD

**Issue by ArcGhh** [idisfkj/android-startup#1]
您好，假如设置了超时等待时间，但是超过了这个等待时间，sdk还没有初始化完成就跳转页面了
这样会不会导致sdk初始化失败啊？

**Comment by idisfkj** [comment]
不会，超时等待是用来解决同步与异步等待时，在主线程执行时间过长，导致应用长时间没反应的一个保底措施。
就算超过等待时间，sdk还是会进行原有的初始化逻辑。
