### ISSUE TITLE
在自己的组件化项目试用了下

### ISSUE THREAD

**Issue by caihuanjian** [idisfkj/android-startup#10]
app module依赖了module1、module2
1、app module中写了AppStartUp，通过app module的manifest配置了provider和AppStartup
2、module1和module2分别有自己的module1StartUp和module2StartUp,并且都在在各自的Manifest中声明了<provider>和<metaData>
3、运行app，manifest的meta-data会合并，但是startup的执行顺序并不是合并后的那个顺序

所以manifest中声明多个StartUp的时候，这几个StartUp是不会按照声明顺序执行的吧？

**Comment by caihuanjian** [comment]
context.packageManager.getProviderInfo(provider, PackageManager.GET_META_DATA)
这个方法拿到的providerInfo.metaData确实不是按照合并之后的manifest的顺序。。manifest的顺序是底层库的meta-data会追加在上层模块的后边。。

**Comment by idisfkj** [comment]
你这不同module间的Startup顺序应该是独立的吧？互相又有依赖顺序？

**Comment by caihuanjian** [comment]
嗯，是我使用的问题
