### ISSUE TITLE
create方法

### ISSUE THREAD

**Issue by HuangJAndroid** [idisfkj/android-startup#13]
初始化是没有返回对象的时候，怎么处理，比如抽象对象
初始化需要的值是application的时候，怎么处理，比如 ARouter.init

**Comment by idisfkj** [comment]
@HuangJAndroid 
1. create方法支持泛型，你可以指定返回的类型
2. 如果你使用的是自动的初始化方法，create方法中的context就代表Application；如果你使用的是手动的初始化方式，create方法中的context就是你build(context)传入的。如果你是在Application中build的，那么这个context就可以代表Application。
