### ISSUE TITLE
如何指定在多进程下初始化

### ISSUE THREAD

**Issue by cowoboy007** [idisfkj/android-startup#2]
只看了主线程和子线程的设置，怎么设置在多进程初始化SDk

**Comment by idisfkj** [comment]
对不起，目前还不支持~
现在正在加入中，请关注之后的版本更新

**Comment by idisfkj** [comment]
> 只看了主线程和子线程的设置，怎么设置在多进程初始化SDk

多进程初始化方式已经支持，请将版本更新到 [v1.4.0](https://github.com/idisfkj/android-startup/releases/tag/1.0.4)

同时v1.0.4还支持线程优先级设置

具体使用详情请查看 [Sample](https://github.com/idisfkj/android-startup/tree/master/app/src/main/java/com/rousetime/sample)
