### ISSUE TITLE
小建议，dependencies能否不使用class

### ISSUE THREAD

**Issue by qiushui95** [idisfkj/android-startup#23]
我是多module项目，各module之间不直接联系。现在只能通过Class.fromName()不是很方便。
如果给每个AndroidStartup加个id，使用dependencies使用id就好了。

**Comment by qiushui95** [comment]
已提pr

**Comment by idisfkj** [comment]
非常感谢你的PR，详情请看这里https://github.com/idisfkj/android-startup/pull/25#issuecomment-995403931

**Comment by qiushui95** [comment]
> 

感谢开源。
