### ISSUE TITLE
延迟初始化的小疑问

### ISSUE THREAD

**Issue by trycatchx** [idisfkj/android-startup#26]
能否支持延迟初始化？

如果支持：
假设 A 延迟初始化， B 依赖了 A ,( A, B 都必须运行在主线程）
那么 B 会等到  A  延迟初始化完毕 ，B 才会执行吗？

**Comment by idisfkj** [comment]
虽然框架没有明确给出延迟初始化的API，但还是可以通过手动分发进行实现

具体可以查看`onDispatch`方法，手动通知依赖完成的场景

**Comment by trycatchx** [comment]
好的
