### ISSUE TITLE
Remove Logging from library

### ISSUE THREAD

**Issue by kuFEAR** [idisfkj/android-startup#27]
Hi, for better performance of your library will be better to delete all of logging code, because it spends time and allocates a lot of objects, and also it uses reflection api for getting class name and etc, usually this does lazily putting arguments and formatted/concatenated on demand.
LoggerLevel settings nohow to helps here, because message will creates even with `LoggerLevel.NONE`
for example:
```kotlin
StartupLogUtils.d("${startup::class.java.simpleName} being dispatching, onMainThread ${startup.callCreateOnMainThread()}.")
```
and somewhere I saw buildString with huge tables)

**Comment by idisfkj** [comment]
Yes, you are right. But I won't delete the logging code because it's useful for development debugging.

However, I will modify the log output mode to solve this problem.

Thank you ~

**Comment by idisfkj** [comment]
It has been updated in version 1.1.0,  [details](https://github.com/idisfkj/android-startup/commit/785ac5df09671501c83ecfb4b3de918b7fd97209)
