### ISSUE TITLE
想问下大家这个库有用在大日活的生产环境吗？

### ISSUE THREAD

**Issue by ld2006203** [idisfkj/android-startup#29]
我们的启动任务比较复杂，await函数爆出大量的anr问题，大家有遇到过这种情况吗？

sun.misc.Unsafe.park(Unsafe.java)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1063)
java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1358)
java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)

**Comment by idisfkj** [comment]
有详细日志吗？

**Comment by yaoxiangshangzou** [comment]
[最新的版本](io.github.idisfkj:android-startup:1.1.0)   遇到了相同问题

**Comment by fansangg** [comment]
有道在用
