### ISSUE TITLE
initializeComponent  延迟接口是否有提供

### ISSUE THREAD

**Issue by trycatchx** [idisfkj/android-startup#31]
initializeComponent  延迟接口是否有提供 或者有类型的功能实现？

**Comment by idisfkj** [comment]
这是一个启动库，不知道你所需要的业务场景是怎样的，但启动库原则上是不存在延迟的，只能说是互相的依赖关系。
延迟也是自己业务的延迟，应该需要在自身业务内部进行处理。但初始化建议还是按正常流程进行。
