### ISSUE TITLE
两种注册方式的context有区别

### ISSUE THREAD

**Issue by ujffdi** [idisfkj/android-startup#33]
Manifest.xml方式里的context，并非Application。
使用网易云信初始化报错：
java.lang.RuntimeException: Unable to create service com.netease.nimlib.service.NimService: java.lang.IllegalStateException: SDK should be config on Application#onCreate()!

在 Application 里 onCreate 调用StartupManager.Builder就不会报错。

但是2种方式还是有差别的，第一种本质是在ContentProvider里初始化，第二种其实还在Application里初始化

**Comment by idisfkj** [comment]
注意
1. 这个根本错误是有的第三方初始化规定了必须在Application.onCreate()中进行
2. 在ContentProvider中的context是能够转化成Application的
3. 第一种与第二种的主要不同点是两者的注册时机，一个是在attachBaseContext()，一个是在onCreate()
4. 第一种与第二种根据业务自我选择
