### ISSUE TITLE
是否支持分组启动任务

### ISSUE THREAD

**Issue by EvilThunder** [idisfkj/android-startup#34]
一般首次启动app时，有些启动任务需要在用户同意隐私服务条款后才能进行。
所以启动任务需要分为两组，首先启动一组不需要授权的任务。当用户点击授权后，再启动另一组需要授权的任务。
当我使用两组startUpBuilder.build(this).start().await()启动任务时，会出现任务依赖的问题。
请问能否实现分组执行启动任务？

**Comment by idisfkj** [comment]
我理解这应该不影响，你的逻辑应该是
1. 你的启动任务应该分两类，需要授权与不需要授权
2. 针对需要授权的任务，在任务中做判断，但他们本质都是启动任务
3. 授权这个动作完了之后（不管授权成功与失败），通过手动触发`onDispatch()`，通知到授权相关的启动任务，让任务执行
4. 执行的任务，内部自身判断授权成功与失败的走向。
