### ISSUE TITLE
manualDispatch的使用问题

### ISSUE THREAD

**Issue by opLW** [idisfkj/android-startup#35]
最近在使用manualDispatch的时候遇到下面两个问题：
根据文档可知，当manualDispatch=true的时候，我们需要通过onDispatch手动通知下一个任务。

- 1.框架设计时，每个任务的create方法是先于下面这段代码执行的
```
    override fun notifyChildren(dependencyParent: Startup<*>, result: Any?, sortStore: StartupSortStore) {
        ....
        sortStore.startupChildrenMap[dependencyParent::class.java.getUniqueKey()]?.forEach {
            sortStore.startupMap[it]?.run {
                onDependenciesCompleted(dependencyParent, result)

                if (dependencyParent.manualDispatch()) {
                    dependencyParent.registerDispatcher(this)
                } else {
                    toNotify()
                }
            }
        }
        ....
    }
```
问题1：
设置了manualDispatch=true的任务，它可能在create的时候就调用onDispatch，也可能在请求结束时通过子线程的Handler回调onDispatch（这里强调子线程的Handler，因为如果是主线程会导致第2个问题，我们下面再讨论）。
如果是后者异步回调，那么没有问题；如果是前者，那么问题来了，由于在create的时候就调用onDispatch，那么此时上述代码还没执行，也就是说下面这段代码里的mObservers还是空的。
```
    override fun onDispatch() {
        mObservers.forEach {
            it.toNotify()
        }
    }
```
因此产生第一个问题：手动调用onDispatch的时机会有问题，如果在create的时候就调用了，那么任务无法继续往下执行了。
解决办法：加多一个变量判断即可
```
    override fun registerDispatcher(dispatcher: Dispatcher) {
        if (mHasDispatched.get()) {
            dispatcher.toNotify()
        } else {
            mObservers.add(dispatcher)
        }
    }

    override fun onDispatch() {
        mObservers.forEach {
            it.toNotify()
        }
        mHasDispatched.set(true)
    }
```

- 2.讲述问题1的时候提到，在请求结束时通过onDispatch进行回调，如果是在主线程会有问题。
我们假设存在任务A和B，他们都是在主线程执行的，任务B依赖任务A，任务A设置了manualDispatch=true，任务A需要等待异步请求结束，通过主线程Handler回调onDispatch。
而框架的设计就是，执行了任务A之后，就马上执行任务B，如果此时任务A还没有调用onDispatch，那么任务B就会调用下面的代码
```
internal class StartupRunnable(
    ...
) : Runnable {

    override fun run() {
        ...
        startup.toWait()
            ...
    }
}
```
由于任务B在主线程执行，这样就会阻塞主线程，而任务A回调onDispatch又需要使用到主线程的handler，这样就会导致死锁：任务A因无法使用主线程而无法结束，任务B因任务A无法结束而阻塞主线程。

**总结** [想问下大家这个库有用在大日活的生产环境吗？ #29](https://github.com/idisfkj/android-startup/issues/29) 应该就是问题2导致的，就是整个任务无法结束而触发了超时。我看那个issue没有下文了，估计是没找到问题的源头，我们也是花了一天才找到问题。
暂时没有找到问题2的解决方案。
其实使用manualDispatch的场景可能是任务B需要依赖任务A的异步请求结果，但manualDispatch的使用会导致整个任务执行变的不可控，综合起来我觉得应该去掉manualDispatch这个功能，让每个任务的开始和结束变的可控。至于任务B依赖任务A的结果的，我觉得可以通过提高任务A的执行优先级以及对A的结果进行缓存来解决。

不知道大佬们有没有更好的解决办法？

**Comment by opLW** [comment]
补充：当前的时间统计是无法统计create到异步onDispatch这一段的，也就导致了问题难以排查。

**Comment by idisfkj** [comment]
@opLW 
1. `manualDispatch = true`，设计理念是针对**任务内部做异步逻辑**，例如网络请求(但本身`create`是在主线程执行)，这个时候当异步获取到结果时调用`onDispatch`，并不会出现`mObservers `为空的情况。所以，如果在create中（严谨的说就是create线程）直接调用`onDispatch`本身就是一个错误的使用方式。针对这种情况，正确的使用方式是不设置`manualDispatch = true`，直接使用正常的逻辑就能满足。
2. A,B任务都在主线程执行，注意这里有两个核心概念。任务执行与任务等待是不同的层面，等待可以阻塞线程也可以不阻塞。例如任务在主线程执行，但它的等待并不需要阻塞主线程。所以针对这个问题，应该让B任务非阻塞等待A任务的通知（`waitOnMainThread = false`）
3. 针对异步时间统计，这里设计到一个时间概念问题，这个时间具体是什么？可以是create任务执行完的时间(当前create所处线程的耗时)；也可以是每个任务的内容自己的耗时（例如网络请求耗时)等等。`Android Startup`使用的是前者。当然角度不一样，结果自然也不一样。

**Comment by opLW** [comment]
@idisfkj 

1. 是的，从设计理念讲没错。但实际使用时，task内部需要根据条件选择同步还是异步，这种需求是存在的，如果使用者不看源码，可能就会犯错了。
2. 是的，你的做法可以解决这个问题。但是从使用者的角度出发，我觉得并不能马上了解到这个问题并作出跟你一样的解法。而且实际情况可能是任务B就是需要在主线程执行，即使任务B甚至后续的所有任务都在子线程执行，最后还有一个`mAwaitCountDownLatch`会阻塞主线程，所以主线程的阻塞在所难免。所以我偏向于`manualDispatch = true`是个潜在的风险，作为一个开源框架。
3. 是的，角度不同结果也会不同。`manualDispatch = true`的设计理念就是允许任务内部做异步逻辑，但问题是这个异步逻辑，本身就会对所有任务的执行总时长造成影响，如果这个异步时间不统计，那我觉得时间统计可能缺少一些准确性，不利于开发者发现问题。

**Comment by idisfkj** [comment]
@opLW 
手动通知的功能是不能取消的，这是一个非常常见的使用场景。
主线程的阻塞与否，根据任务来决定，更多的是由使用者自身控制。
同时避免使用困扰，已经提供了详细的代码示例与文档。

当然，一些可能存在混淆的概念，是有必须突出强调一下，后续可以完善一下

**Comment by idisfkj** [comment]
也欢迎提交优质的PR
