### ISSUE TITLE
如何实现初始化的暂停与恢复？

### ISSUE THREAD

**Issue by Jorah1012** [idisfkj/android-startup#36]
现在app都需要用户同意隐私协议之后才能进入app，这样就会出现一种特殊的情况：先初始化基础模块，然后暂停，等待用户同意隐私，之后会继续初始化其它配置好的模块

**Comment by idisfkj** [comment]
#34 可以看下这个

**Comment by Jorah1012** [comment]
多谢，通过手动触发搞定
