### ISSUE TITLE
CountDownLatch.await 报错

### ISSUE THREAD

**Issue by yaoxiangshangzou** [idisfkj/android-startup#38]
一个偶发的错误 ，最新版本代码，启动时候大约有9个子线程任务是waitOnMainThread为true

signal 7 (SIGBUS), code 0 (SI_USER), fault addr --------
    x0  fffffffffffffffc  x1  0000000000000080  x2  0000000000000002  x3  0000007fed8acb58
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000000
    x8  0000000000000062  x9  000000001dccd25d  x10 0000000000000000  x11 0000000000000000
    x12 0000000000003c26  x13 000000001f4c2e74  x14 0000007fed8acc30  x15 000000004cec4ec5
    x16 0000006f6c00f658  x17 0000007217272540  x18 000000722dcb0000  x19 b4000070e019503c
    x20 b4000070e0195010  x21 00000000d09d305d  x22 0000000000000000  x23 0000000000000004
    x24 000000005c000000  x25 000000722d257000  x26 0000006f6c215000  x27 000000722d257000
    x28 0000006f6c216000  x29 0000007fed8acb70
    lr  0000006f6be697f4  sp  0000007fed8acb40  pc  0000007217272560  pst 0000000040001000
backtrace:
  #00 pc 000000000004f560  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32) (BuildId: c4ad377c1afe6c3cdcbf318f3b21cd88)
      #01 pc 00000000006697f0  /apex/com.android.art/lib64/libart.so (art::Thread::Park(bool, long)+1088) (BuildId: ddb65a0ad7a10ff0118559561179de09)
      #02 pc 00000000005a993c  /apex/com.android.art/lib64/libart.so (art::Unsafe_park(_JNIEnv*, _jobject*, unsigned char, long)+652) (BuildId: ddb65a0ad7a10ff0118559561179de09)
      #03 pc 0000000000094504  /system/framework/arm64/boot.oat (art_jni_trampoline+116) (BuildId: d4244adc141b70c1f3f3c5e03e356ec46a43d525)
      #04 pc 000000000020a910  /apex/com.android.art/lib64/libart.so (nterp_helper+5648) (BuildId: ddb65a0ad7a10ff0118559561179de09)
      #05 pc 000000000022ba24  /apex/com.android.art/javalib/core-oj.jar (java.util.concurrent.locks.LockSupport.parkNanos+32)
      #06 pc 0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: ddb65a0ad7a10ff0118559561179de09)
      #07 pc 000000000022aafe  /apex/com.android.art/javalib/core-oj.jar (java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos+134)
      #08 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: ddb65a0ad7a10ff0118559561179de09)
      #09 pc 000000000022aefc  /apex/com.android.art/javalib/core-oj.jar (java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos+24)
      #10 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: ddb65a0ad7a10ff0118559561179de09)
      #11 pc 000000000020d87e  /apex/com.android.art/javalib/core-oj.jar (java.util.concurrent.CountDownLatch.await+14)
      #12 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: ddb65a0ad7a10ff0118559561179de09)
      #13 pc 00000000004c922e  /system/priv-app/***/***.apk (com.tal.znxx.lib_init_manager.StartupManager.await+46)
      #14 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: ddb65a0ad7a10ff0118559561179de09)
      #15 pc 00000000004c855c  /system/priv-app/***/***.apk (com.tal.znxx.lib_init_manager.InitManager.doInit+216)

**Comment by idisfkj** [comment]
有后续吗？我这边暂时close了，如果有进展可补充
