### ISSUE TITLE
初始化问题

### ISSUE THREAD

**Issue by dongliwu520** [idisfkj/android-startup#4]
1、如果异步执行初始化，会不会出现还没初始化完就到首页了，但是首页又需要这个三方库，导致执行失败？
2、初始化时需要传appliction时怎么办？

**Comment by idisfkj** [comment]
1. 如果你需要异步等待的话，你可以设置`waitOnMainThread(): Boolean = true`，这样可以保证在首页启动时该异步任务已经完成。
2. 不管是手动还是自动配置`Android Startup`，`Android Startup`初始化都是在`Application`创建之后再启动的，所以如果需要`Application`实例可以通过全局单例的方式获取。
