### ISSUE TITLE
异常问题

### ISSUE THREAD

**Issue by dongliwu520** [idisfkj/android-startup#5]
使用了这个库之后, bugly收到了很多异常信息..
#56515 SIGABRT  #86512 SIGABRT 很多类似的问题

#00 pc 0001afb8 /system/lib/libc.so (abort+100) [armeabi-v8]
2 #01 pc 0035b311 /system/lib/libart.so (art::Runtime::Abort(char const*)+392) [armeabi-v8]
.....
com.xxxx.constants.InitTool.initPush(InitTool.java:69)
com.xxxx..common.startup.InitPushStartup.create(InitPushStartup.java:28)
com.xxxx..common.startup.InitPushStartup.create(InitPushStartup.java:17)

代码：
public Boolean create(@NotNull Context context) {
    InitTool.initPush(applictaion);    ---->> Line 28
    return null;
}

**Comment by dongliwu520** [comment]
有一个初始化时间为什么是 负数

    |=================================================================
    |      Startup Name       |   InitOkHttpStartup
    | ----------------------- | --------------------------------------
    |   Call On Main Thread   |   false
    | ----------------------- | --------------------------------------
    |   Wait On Main Thread   |   false
    | ----------------------- | --------------------------------------
    |       Cost Times        |   -874667751 ms
    |=================================================================

**Comment by idisfkj** [comment]
能给出更详情的异常信息吗？或者使用的具体相关代码

**Comment by dongliwu520** [comment]
能加Q细聊吗？ 我也不清楚这个问题是否因为这个库导致的..   7907716

**Comment by dongliwu520** [comment]
> 能给出更详情的异常信息吗？或者使用的具体相关代码

能加Q细聊吗？ 我也不清楚这个问题是否因为这个库导致的.. 7907716
