### ISSUE TITLE
仓库引用 出现jar包冲突 constraintLayout jar版本不一致导致的冲突

### ISSUE THREAD

**Issue by pichsy** [idisfkj/android-startup#7]
startup aar包如果没有使用到这个包，希望能从maven关联的引用中删除。本人无奈，只能下载源码，编译成jar包使用。本人认为上传成jar包足够了，无冗杂引用，更干净，不影响项目中其他库引用的版本。

**Comment by pichsy** [comment]
startup aar包如果没有使用到这个包，希望能重maven关联的引用中删除。本人无奈，只能下载源码，编译成jar包使用。本人认为上传成jar包足够了，无冗杂引用，更干净，不影响项目中其他库引用的版本。

**Comment by idisfkj** [comment]
> startup aar包如果没有使用到这个包，希望能从maven关联的引用中删除。本人无奈，只能下载源码，编译成jar包使用。本人认为上传成jar包足够了，无冗杂引用，更干净，不影响项目中其他库引用的版本。

你确定是`Startup`的问题？因为`Startup`里面本来就是不包含ConstraintLayout的依赖包的

**Comment by pichsy** [comment]
可能是项目太复杂了，gradle版本太老了，忽略吧，谢谢！~
