### ISSUE TITLE
多进程task，为什么要直接在AndroidStartup中指定？

### ISSUE THREAD

**Issue by YangCheung** [idisfkj/android-startup#8]
多进程都需要启动的task要怎么处理

 `
 if ((TextUtils.isEmpty(process) && ProcessUtils.isMainProcess(context)) || ProcessUtils.isMultipleProcess(context, process)) {
                    realStartupList.add(it)
                    if (it.waitOnMainThread() && !it.callCreateOnMainThread()) {
                        mNeedAwaitCount.incrementAndGet()
                    }
                }
 `

**Comment by idisfkj** [comment]
> 多进程都需要启动的task要怎么处理
> 
> `if ((TextUtils.isEmpty(process) && ProcessUtils.isMainProcess(context)) || ProcessUtils.isMultipleProcess(context, process)) { realStartupList.add(it) if (it.waitOnMainThread() && !it.callCreateOnMainThread()) { mNeedAwaitCount.incrementAndGet() } }`

1. 多进程间的数据是不共享的，所以为了让对应的`AndroidStartup`初始化中的数据能够被访问到，必须明确指定当前`AndroidStartup`作用的进程。
2. 对于多个进行都要启动同一个`task`，如果这个`task`可以共享，那你可以放到主线程启动，自己去做进程通信；如果这个`task`不能共享，那么你目前只能不同进程对应不同`task`。
3. 当然如果你有更好的方案，欢迎提建议~

**Comment by YangCheung** [comment]
不同进程初始化流程可能差异很大。其中很多模块各进程也都需要，例如日志，工具类等。
比较灵活的方式是各进程空间独立启动StartupManager（1.0.3版本），而不是通过限制task所在进程来处理

**Comment by idisfkj** [comment]
> 不同进程初始化流程可能差异很大。其中很多模块各进程也都需要，例如日志，工具类等。
> 比较灵活的方式是各进程空间独立启动StartupManager（1.0.3版本），而不是通过限制task所在进程来处理

这样的话重复性太重，而且对于在`AndroidManifest`中自动注册的启动方式也不友好。
我认为比较好的方式是为`MultipleProcess`支持多个进程设置。

**Comment by YangCheung** [comment]
`
        (TextUtils.isEmpty(process) && ProcessUtils.isMainProcess(context))
`
对于这个判断，可以放开主进程判断逻辑，没有指定进程时，默认在所有进程初始化。相对更灵活

**Comment by idisfkj** [comment]
后续会升个小版本来优化这个问题

**Comment by idisfkj** [comment]
该优化已更新到[v1.0.6](https://github.com/idisfkj/android-startup/releases/tag/1.0.6)
