### ISSUE TITLE
接入项目试了下,

### ISSUE THREAD

**Issue by 424385117** [idisfkj/android-startup#9]
并没有明显提高,原先是点击图标到界面显示4s,接入之后还是4s,提升不是很明显

**Comment by idisfkj** [comment]
这样要看你的项目，如果之前初始化的都是在主线程，接了之后还是在主线程，或者说`ContentnProvider`也没怎么用，那自然没多大提升。

需要在主线程初始化的时间是逃不掉的。

**Comment by idisfkj** [comment]
还有这个项目的本质是帮助大家维护项目的初始化任务，更好的管理同步任务与异步任务之间的依赖关系；而加快启动速度，更多的是由大家的自身项目的任务决定的。

**Comment by 424385117** [comment]
> 还有这个项目的本质是帮助大家维护项目的初始化任务，更好的管理同步任务与异步任务之间的依赖关系；而加快启动速度，更多的是由大家的自身项目的任务决定的。

嗯,我在startup里面 对于那些非启动项做了些延时启动 ,应用打开黑屏 从原先的4.6s 缩短至 1.37s 提升挺大的
